python:
  - 3.7.* *_cpython  # [x86_64]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
python_impl:
  - cpython    # [x86_64]
  - cpython
  - cpython
  - cpython
numpy:
  - 1.20    # [x86_64]
  - 1.20
  - 1.20
  - 1.21
