python:
  # part of a zip_keys: python, is_python_min
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
is_python_min:
  # part of a zip_keys: python, is_python_min
  - false
  - true
  - false
  - false
  - false
